#!/usr/bin/env python3
"""Generate thin platform adapters from a canonical template and policy revision."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

MARKER = "<!-- Generated by charm-repository-documentation-normalizer;"


def digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()[:16]


def platform_content(kind: str, common: str) -> str:
    if kind == "cursor":
        return "---\ndescription: Route repository documentation and follow canonical agent policy\nalwaysApply: true\n---\n\n" + common
    if kind == "copilot":
        return common + "\nFor path-specific guidance, use `.github/instructions/` only when generated from a scoped canonical policy.\n"
    return common


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--templates", type=Path, required=True)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    if args.write == args.check:
        parser.error("choose exactly one of --write or --check")
    root = args.root.resolve()
    policy = root / "docs/repository/agent-policy.md"
    manifest_path = root / "docs/repository/manifest.yaml"
    template = args.templates.resolve() / "adapter.md"
    if not policy.is_file() or not manifest_path.is_file():
        parser.error("create docs/repository/agent-policy.md and manifest.yaml before generating adapters")
    if not template.is_file():
        parser.error(f"missing adapter template: {template}")

    policy_hash = digest(policy.read_bytes())
    template_bytes = template.read_bytes()
    template_hash = digest(template_bytes)
    header = f"{MARKER} policy-sha256={policy_hash}; template-sha256={template_hash}; edit canonical sources instead. -->\n"
    common = template_bytes.decode("utf-8")
    targets = {
        "AGENTS.md": "generic",
        "CLAUDE.md": "generic",
        "GEMINI.md": "generic",
        ".cursor/rules/charm-repository-docs.mdc": "cursor",
        ".github/copilot-instructions.md": "copilot",
    }
    stale, refused = [], []
    for relative, kind in targets.items():
        target = root / relative
        desired = header + platform_content(kind, common)
        existing = target.read_text(encoding="utf-8") if target.exists() else ""
        if args.check:
            if existing != desired:
                stale.append(relative)
            continue
        if target.exists() and not existing.startswith(MARKER) and not args.force:
            refused.append(relative)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(desired, encoding="utf-8")
        print(f"wrote {relative}")
    if refused:
        print("refused non-generated files: " + ", ".join(refused))
        return 2
    if stale:
        print("stale or missing adapters: " + ", ".join(stale))
        return 1
    print("adapters are current" if args.check else "adapters generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
