#!/usr/bin/env python3
"""Validate normalized docs, manifests, freshness triggers, links, and adapters."""
from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
from pathlib import Path

from charm_docs_common import frontmatter, manifest, path_matches

REQUIRED_BY_KIND = {
    "index": ["At a glance"],
    "architecture": ["Responsibility"],
    "contract": ["Invariants", "Verification"],
    "flow": ["Steps", "Verification"],
    "procedure": ["Steps", "Verification"],
    "decision": ["Context", "Decision", "Consequences"],
}
GENERATED = ["AGENTS.md", "CLAUDE.md", "GEMINI.md", ".cursor/rules/charm-repository-docs.mdc", ".github/copilot-instructions.md"]
MARKER = "<!-- Generated by charm-repository-documentation-normalizer;"


def git_lines(root: Path, command: list[str]) -> set[str]:
    try:
        output = subprocess.check_output(command, cwd=root, text=True, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, FileNotFoundError):
        return set()
    return {line.strip() for line in output.splitlines() if line.strip()}


def changed_paths(root: Path, base: str | None) -> set[str]:
    changed: set[str] = set()
    if base:
        changed |= git_lines(root, ["git", "diff", "--name-only", f"{base}...HEAD", "--"])
    else:
        changed |= git_lines(root, ["git", "diff", "--name-only", "HEAD", "--"])
        changed |= git_lines(root, ["git", "diff", "--cached", "--name-only", "--"])
        changed |= git_lines(root, ["git", "ls-files", "--others", "--exclude-standard"])
    return changed


def list_values(data: dict[str, object], key: str) -> list[str]:
    value = data.get(key, [])
    return [str(item) for item in value] if isinstance(value, list) else []


def policy_digest(policy: Path) -> str:
    return hashlib.sha256(policy.read_bytes()).hexdigest()[:16]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--changed", action="store_true")
    parser.add_argument("--base")
    parser.add_argument("--require-adapters", action="store_true")
    parser.add_argument("--enforce-freshness", action="store_true")
    parser.add_argument("--reviewed-no-change", action="append", default=[], metavar="DOCUMENT_ID")
    args = parser.parse_args()
    root = args.root.resolve()
    docs_root = root / "docs/repository"
    root_manifest = docs_root / "manifest.yaml"
    policy = docs_root / "agent-policy.md"
    errors: list[str] = []
    warnings: list[str] = []
    doc_metadata: dict[str, tuple[Path, dict[str, object]]] = {}
    indexed_ids: set[str] = set()

    if not root_manifest.is_file():
        errors.append("missing docs/repository/manifest.yaml")
    if not policy.is_file():
        errors.append("missing docs/repository/agent-policy.md")

    for file in docs_root.rglob("*.md") if docs_root.is_dir() else []:
        data = frontmatter(file)
        relative = file.relative_to(root).as_posix()
        if not data:
            warnings.append(f"{relative}: no frontmatter")
            continue
        if data.get("_error"):
            errors.append(f"{relative}: {data['_error']}")
            continue
        doc_id = str(data.get("id", ""))
        if not doc_id:
            errors.append(f"{relative}: missing id")
        elif doc_id in doc_metadata:
            errors.append(f"duplicate document id: {doc_id}")
        else:
            doc_metadata[doc_id] = (file, data)
        body = str(data.get("_body", ""))
        kind = str(data.get("kind", ""))
        for section in REQUIRED_BY_KIND.get(kind, []):
            if f"## {section}" not in body:
                warnings.append(f"{relative}: missing recommended section {section}")
        for source in list_values(data, "source_paths") + list_values(data, "scope"):
            literal = source.replace("**", "").replace("*", "").rstrip("/")
            if literal and not any(root.glob(source)) and not (root / literal).exists():
                warnings.append(f"{relative}: evidence/scope path has no match: {source}")
        for target in re.findall(r"\[[^]]+\]\(([^)]+)\)", body):
            if target.startswith(("http://", "https://", "#", "mailto:")):
                continue
            target_path = (file.parent / target.split("#", 1)[0]).resolve()
            if not target_path.exists():
                errors.append(f"{relative}: broken local link: {target}")

    child_manifests: set[str] = set()
    referenced_child_manifests: set[str] = set()
    for manifest_path in sorted(docs_root.rglob("manifest.yaml")) if docs_root.is_dir() else []:
        parsed = manifest(manifest_path)
        manifest_relative = manifest_path.relative_to(root).as_posix()
        if manifest_path != root_manifest:
            child_manifests.add(manifest_relative)
        parent = str(parsed.get("parent", ""))
        if parent and not (root / parent).is_file():
            errors.append(f"{manifest_relative}: missing parent manifest: {parent}")
        for workspace in parsed.get("workspaces", []):
            if isinstance(workspace, dict) and workspace.get("manifest"):
                workspace_manifest = str(workspace["manifest"])
                referenced_child_manifests.add(workspace_manifest)
                if not (root / workspace_manifest).is_file():
                    errors.append(f"{manifest_relative}: missing workspace manifest: {workspace_manifest}")
        for entry in parsed.get("documents", []):
            if not isinstance(entry, dict):
                continue
            doc_id = str(entry.get("id", ""))
            doc_path = str(entry.get("path", ""))
            if not doc_id or not doc_path:
                errors.append(f"{manifest_relative}: document entry requires id and path")
                continue
            if doc_id in indexed_ids:
                errors.append(f"duplicate manifest document id: {doc_id}")
            indexed_ids.add(doc_id)
            target = root / doc_path
            if not target.is_file():
                errors.append(f"{manifest_relative}: missing document path: {doc_path}")
                continue
            metadata = frontmatter(target)
            if metadata.get("id") != doc_id:
                errors.append(f"{manifest_relative}: id mismatch for {doc_path}: {doc_id} != {metadata.get('id', '<missing>')}")
            if entry.get("kind") and metadata.get("kind") != entry.get("kind"):
                errors.append(f"{manifest_relative}: kind mismatch for {doc_path}")

    for doc_id, (file, _) in doc_metadata.items():
        if doc_id not in indexed_ids:
            warnings.append(f"{file.relative_to(root)}: document is not indexed by a manifest")
    for missing in sorted(child_manifests - referenced_child_manifests):
        warnings.append(f"{missing}: child manifest is not routed by a workspaces entry")

    changed = changed_paths(root, args.base) if args.changed else set()
    if args.changed and not changed:
        warnings.append("no changed paths found; provide --base in CI and ensure checkout history is available")
    for doc_id, (file, data) in doc_metadata.items():
        triggers = list_values(data, "update.triggers")
        impacted = sorted(path for path in changed if any(path_matches(pattern, path) for pattern in triggers))
        if not impacted:
            continue
        relative = file.relative_to(root).as_posix()
        if relative in changed:
            continue
        if doc_id in args.reviewed_no_change:
            continue
        message = f"{doc_id}: trigger paths changed without a documentation update or --reviewed-no-change ({', '.join(impacted[:3])})"
        if args.enforce_freshness and data.get("update.policy") in {"required-review", "required-update"}:
            errors.append(message)
        else:
            warnings.append(message)

    if args.require_adapters and policy.is_file():
        expected_hash = policy_digest(policy)
        for relative in GENERATED:
            file = root / relative
            if not file.is_file():
                errors.append(f"missing generated adapter: {relative}")
                continue
            first_line = file.read_text(encoding="utf-8", errors="replace").splitlines()[0]
            if not first_line.startswith(MARKER) or f"policy-sha256={expected_hash}" not in first_line:
                errors.append(f"stale generated adapter: {relative}")

    for item in warnings:
        print("WARN  " + item)
    for item in errors:
        print("ERROR " + item)
    print(f"validated {len(doc_metadata)} documents and {len(indexed_ids)} manifest entries; {len(errors)} error(s), {len(warnings)} warning(s)")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
