import { openSync, closeSync, writeFileSync, readFileSync, existsSync, renameSync, fsyncSync, unlinkSync, statSync } from "node:fs";
import { dirname, basename, join } from "node:path";
import type { CharmPaths } from "../paths.ts";

/** A COORDINATION.md lock older than this is treated as stale and stolen. A real
 *  write holds the lock for microseconds, so any lock lingering this long is a
 *  leak from a writer that crashed mid-write — not live contention. */
const LOCK_STALE_MS = 5000;

const HEADER =
  "# COORDINATION.md\n\n" +
  "_Live ticket board, auto-generated by charmd. One row per ticket still in play " +
  "(open, in-flight, or failed); completed and cancelled tickets drop off. `agent` shows the " +
  "sub-agent currently on the ticket, or `-` if it is unassigned. Each ticket's full plan, " +
  "status history, and orchestrator messages live in its own file " +
  "(`.charm/tickets/<id>.md`). Do not edit by hand._\n\n";

/** One row of the coordination board: a single live ticket, its pipeline stage and
 *  status, and the sub-agent currently working it (if any). Fully derived from the
 *  sqlite index + agent registry by the caller — the writer only renders. */
export type CoordRow = {
  ticket_id: string;
  about: string;
  stage: string;
  status: string;
  /** Id of the live sub-agent on this ticket, or null if unassigned. */
  agent_id: string | null;
  /** That agent's state (running/blocked/...), or null if unassigned. */
  agent_state: string | null;
};

/**
 * Maintains COORDINATION.md as a compact index, NOT a per-agent dossier. The old
 * model wrote each agent's full plan + an accumulating note log + a JSON dump
 * here, so the file ballooned over a run. Now the verbose history lives in each
 * ticket file (see TicketStore.appendLog); this file is just a dashboard: ticket
 * -> brief description -> assigned agent -> state.
 *
 * Because every row is derivable from the registry + ticket store, there's no
 * parse-back: the daemon recomputes the full row set and we rewrite the whole
 * (small) file atomically on each change.
 */
export class CoordinationWriter {
  private lockPath: string;
  constructor(private paths: CharmPaths) {
    this.lockPath = paths.coordinationMd + ".lock";
  }

  /** Render the index from the given rows, replacing the file atomically. */
  write(rows: CoordRow[]) {
    this.withLock(() => {
      let out = HEADER;
      if (rows.length === 0) {
        out += "_No live tickets — everything is complete or nothing has been created yet._\n";
      } else {
        out += "| ticket | about | stage | status | agent |\n| --- | --- | --- | --- | --- |\n";
        for (const r of rows) {
          const about = r.about.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
          const agent = r.agent_id ? `\`${r.agent_id}\` (${r.agent_state})` : "-";
          out += `| [${r.ticket_id}.md](tickets/${r.ticket_id}.md) | ${about} | ${r.stage} | ${r.status} | ${agent} |\n`;
        }
      }
      this.atomicWrite(this.paths.coordinationMd, out);
    });
  }

  read(): string {
    return existsSync(this.paths.coordinationMd) ? readFileSync(this.paths.coordinationMd, "utf8") : "";
  }

  /** Remove a leftover lock file from a prior daemon that crashed mid-write.
   *  The lock is held only for the microseconds of one synchronous write, so a
   *  lock present at startup can only be stale. withLock() now self-heals a stale
   *  lock anyway (it steals one older than LOCK_STALE_MS), so this is just a tidy
   *  boot-time cleanup that lets the very first refresh proceed without waiting
   *  out the staleness window. Safe to call once at startup, after the
   *  single-daemon pidfile guard has run. */
  clearStaleLock(): void {
    try { unlinkSync(this.lockPath); } catch { /* nothing to clear */ }
  }

  private atomicWrite(path: string, text: string) {
    const tmp = join(dirname(path), `.${basename(path)}.tmp.${process.pid}`);
    const fd = openSync(tmp, "w");
    try {
      writeFileSync(fd, text);
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
    renameSync(tmp, path);
  }

  private withLock(fn: () => void): void {
    let fd: number;
    try {
      fd = openSync(this.lockPath, "wx");
    } catch (e: any) {
      if (e.code !== "EEXIST") throw e;
      // The lock is held. NEVER busy-wait here: COORDINATION.md is written only by
      // this single-threaded daemon and each write is synchronous (it never yields
      // mid-write), so two in-process writes can't actually interleave — there is
      // no real in-process contention to wait out. A held lock therefore means
      // either a prior writer crashed and leaked it, or (only if some other
      // process writes this file) a live cross-process writer. A synchronous spin
      // would freeze the whole event loop and starve every RPC, so instead:
      // steal a stale lock, otherwise skip this refresh. The board is fully
      // regenerated on the next change, so a skipped write self-heals.
      let stale: boolean;
      try {
        stale = Date.now() - statSync(this.lockPath).mtimeMs > LOCK_STALE_MS;
      } catch {
        stale = true; // lock vanished between open and stat -> treat as free
      }
      if (!stale) {
        console.error("[charmd] COORDINATION.md lock held; skipping this refresh (board self-heals on the next change).");
        return;
      }
      console.error("[charmd] COORDINATION.md lock looks stale; stealing it.");
      try { unlinkSync(this.lockPath); } catch { /* already gone */ }
      try {
        fd = openSync(this.lockPath, "wx");
      } catch {
        console.error("[charmd] could not acquire COORDINATION.md lock after stealing a stale one; skipping refresh.");
        return;
      }
    }
    try {
      fn();
    } finally {
      closeSync(fd);
      try { unlinkSync(this.lockPath); } catch { /* ignore */ }
    }
  }
}
