import { openSync, closeSync, writeFileSync, readFileSync, existsSync, renameSync, fsyncSync, unlinkSync } from "node:fs";
import { dirname, basename, join } from "node:path";
import type { CharmPaths } from "../paths.ts";

const HEADER =
  "# COORDINATION.md\n\n" +
  "_Live index, auto-generated by charmd. One row per ticket that has a live agent. " +
  "Each ticket's full plan, status history, and orchestrator messages live in its own " +
  "file (`.charm/tickets/<id>.md`). Do not edit by hand._\n\n";

/** One row of the coordination index: which agent holds which ticket, what it's
 *  about, and the agent's live state. Fully derived from daemon state by the
 *  caller — the writer only renders. */
export type CoordRow = {
  ticket_id: string;
  about: string;
  agent_id: string;
  state: string;
};

/**
 * Maintains COORDINATION.md as a compact index, NOT a per-agent dossier. The old
 * model wrote each agent's full plan + an accumulating note log + a JSON dump
 * here, so the file ballooned over a run. Now the verbose history lives in each
 * ticket file (see TicketStore.appendLog); this file is just a dashboard: ticket
 * -> brief description -> assigned agent -> state.
 *
 * Because every row is derivable from the registry + ticket store, there's no
 * parse-back: the daemon recomputes the full row set and we rewrite the whole
 * (small) file atomically on each change.
 */
export class CoordinationWriter {
  private lockPath: string;
  constructor(private paths: CharmPaths) {
    this.lockPath = paths.coordinationMd + ".lock";
  }

  /** Render the index from the given rows, replacing the file atomically. */
  write(rows: CoordRow[]) {
    this.withLock(() => {
      let out = HEADER;
      if (rows.length === 0) {
        out += "_No tickets are currently assigned to an agent._\n";
      } else {
        out += "| ticket | about | agent | state |\n| --- | --- | --- | --- |\n";
        for (const r of rows) {
          const about = r.about.replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
          out += `| [${r.ticket_id}.md](tickets/${r.ticket_id}.md) | ${about} | \`${r.agent_id}\` | ${r.state} |\n`;
        }
      }
      this.atomicWrite(this.paths.coordinationMd, out);
    });
  }

  read(): string {
    return existsSync(this.paths.coordinationMd) ? readFileSync(this.paths.coordinationMd, "utf8") : "";
  }

  private atomicWrite(path: string, text: string) {
    const tmp = join(dirname(path), `.${basename(path)}.tmp.${process.pid}`);
    const fd = openSync(tmp, "w");
    try {
      writeFileSync(fd, text);
      fsyncSync(fd);
    } finally {
      closeSync(fd);
    }
    renameSync(tmp, path);
  }

  private withLock<T>(fn: () => T): T {
    const start = Date.now();
    let fd: number | null = null;
    while (true) {
      try {
        fd = openSync(this.lockPath, "wx");
        break;
      } catch (e: any) {
        if (e.code !== "EEXIST") throw e;
        if (Date.now() - start > 5000) throw new Error("COORDINATION.md lock timeout");
        Bun.sleepSync(20);
      }
    }
    try {
      return fn();
    } finally {
      if (fd !== null) closeSync(fd);
      try { unlinkSync(this.lockPath); } catch { /* ignore */ }
    }
  }
}
